/** @format */

import type { Metadata } from 'next'
import './globals.css'
import { AppProviders } from './AppProviders'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="mdl-js">
      <body className="font-blink antialiased">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  )
}
